#
# Time
#

- name: Configure time zone
  ansible.builtin.file:
    path: /etc/localtime
    state: link
    src: /usr/share/zoneinfo/{{ time.timezone }}
  become: true

- name: Enable time synchronization
  ansible.builtin.service:
    name: systemd-timesyncd.service
    state: started
    enabled: true
  become: true

#
# Localization
#

- name: Configure supported locales
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: '^#?{{ localization.locale }}\s+(.+)'
    backrefs: true
    line: '{{ localization.locale }} \1'
  notify:
    - Regenerate locales
  become: true

- name: Configure locale
  ansible.builtin.copy:
    dest: /etc/locale.conf
    content: |
      LANG={{ localization.locale }}
    mode: u=rw,g=r,o=r
  become: true

- name: Configure console keyboard layout
  ansible.builtin.copy:
    dest: /etc/vconsole.conf
    content: |
      KEYMAP={{ localization.keymap }}
    mode: u=rw,g=r,o=r
  become: true

#
# Network
#

- name: Configure hostname
  ansible.builtin.copy:
    dest: /etc/hostname
    content: |
      {{ network.hostname }}
    mode: u=rw,g=r,o=r

- name: Configure networks
  ansible.builtin.template:
    dest: /etc/systemd/network/{{ item | basename }}
    src: "{{ item }}"
    mode: u=rw,g=r,o=r
  with_fileglob: '../templates/systemd-networkd/*'
  become: true

- name: Enable network manager
  ansible.builtin.service:
    name: systemd-networkd.service
    state: started
    enabled: true
  become: true

- name: Configure DNS resolver
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: link
    src: /run/systemd/resolve/stub-resolv.conf
  become: true

- name: Enable DNS resolver
  ansible.builtin.service:
    name: systemd-resolved.service
    state: started
    enabled: true
  become: true

#
# Boot loader
#

- name: Configure systemd-boot
  ansible.builtin.copy:
    dest: /boot/loader/loader.conf
    src: ../templates/systemd-boot/loader.conf
    mode: u=rwx,g=rx,o=rx
  become: true


- name: Configure systemd-boot entries
  ansible.builtin.template:
    dest: /boot/loader/entries/{{ item | basename }}
    src: "{{ item }}"
    mode: u=rwx,g=rx,o=rx
  with_fileglob: '../templates/systemd-boot/entries/*'
  become: true

#
# Packages
#

- name: Install core packages
  community.general.pacman:
    name:
      # core
      - base
      - base-devel
      - linux
      - linux-firmware
      # documentation
      - man-db
      - man-pages
      - texinfo
      # misc
      - git
    reason: explicit
    reason_for: all
    state: present

# vim: ft=yaml.ansible
