# https://wiki.archlinux.org/title/VMware/Install_Arch_Linux_as_a_guest

- name: All
  become: true
  block:
    - name: Install packages
      community.general.pacman:
        name:
          - open-vm-tools
        reason: explicit
        reason_for: all
        state: present

    - name: Enable services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - vmtoolsd.service
        - vmware-vmblock-fuse.service

    - name: Install `vmware-shared-folder@.service`
      ansible.builtin.copy:
        dest: /etc/systemd/system/vmware-shared-folder@.service
        src: vmware-shared-folder@.service
        mode: u=rw,g=r,o=r

# vim: ft=yaml.ansible
