# vim: ft=yaml.ansible

- name: Parse packages var
  ansible.builtin.set_fact:
    packages: "{{ common_packages | from_packages }}"

- name: Install paru-bin
  vars:
    aur_name: paru-bin
  ansible.builtin.include_role:
    name: aur

- name: Sync packages
  vars:
    paru_packages: "{{ packages.packages }}"
  ansible.builtin.include_role:
    name: paru

- name: Activate services
  become: true
  with_items: "{{ packages.services }}"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true

- name: Install `vmware-shared-folder@.service`
  when: "ansible_facts['virtualization_type'] | lower == 'vmware'"
  ansible.builtin.copy:
    dest: /etc/systemd/system/vmware-shared-folder@.service
    src: vmware-shared-folder@.service
    mode: u=rw,g=r,o=r
