- name: Arch Linux
  when: ansible_facts['os_family']|lower == 'archlinux'
  ansible.builtin.import_tasks: ./archlinux.yaml

- name: VMWare
  when: ansible_facts['virtualization_type']|lower == 'vmware'
  ansible.builtin.import_tasks: ./vmware.yaml

# vim: ft=yaml.ansible
