#!/usr/bin/env bash

# Usage: use java <version>
#
# Loads the specified Java version into the environment.
use_java() {
	local version="$1"
	if [[ -z "$version" ]]; then
		log_error "You must specify a <version> parameter"
		return 1
	fi

	local java_prefix="/usr/lib/jvm/java-${version}-openjdk"
	if [[ ! -d "$java_prefix" ]]; then
		log_error "Unable to find java version $version"
		return 1
	fi

	export JAVA_HOME="$java_prefix"
	PATH_add "$JAVA_HOME/bin"
	PATH_add "$JAVA_HOME/jre/bin"

    log_status "Successfully loaded Java $(java -version | head -n 1)"
}

# Usage: use nvm [version]
#
# Loads the specified node version using `nvm`, if the `nvm` command is not
# available, it will try sourcing it at `NVM_SH` with a fallback to a default
# location.
use_nvm() {
	# try to source nvm if not available
	if ! has nvm; then
		local nvm_sh="${NVM_SH:-/usr/share/nvm/init-nvm.sh}"
		if ! [[ -e "$nvm_sh" ]]; then
			log_error "Command \"nvm\" not available, either source it in your .bashrc or configure the \"NVM_SH\" environment variable."
			return 1
		fi

		source "$nvm_sh"
	fi

	nvm use "$@"
}
