#!/usr/bin/env zsh

alias ca="cargo"
alias cat="bat"
alias dc="docker compose"
alias gw="./gradlew"
alias pacman="paru"
alias vim="nvim"
alias vimc="(cd ~/.config/nvim && nvim)"
alias wget="wget -q -c -w 3 --show-progress"
alias xc="wl-copy"
alias xp="wl-paste"

# git
alias g="git"
alias ga="git add"
alias gaf="git fzf-add"
alias gap="git add --patch"
alias gb="git branch"
alias gba="git branch --all --verbose"
alias gbD="git branch -D"
alias gbd="git branch --delete"
alias gbm="git branch --move"
alias gbr="git branch --remote"
alias gc="git commit --verbose"
alias gca="git commit --all --verbose"
alias gcam="git commit --all --message"
alias gch="git checkout"
alias gcm="git commit --message"
alias gcp="git cherry-pick"
alias gd="git diff"
alias gdc="git diff --cached"
alias gdt="git difftool"
alias gf="git fetch"
alias gfa="git fetch --all"
alias gfm="git pull"
alias gfr="git pull --rebase"
alias gl="git log"
alias glg="git lg"
alias glga="git lg --all"
alias glgs="git lg -10"
alias gm="git merge --no-ff"
alias gmf="git merge --ff-only"
alias gms="git merge --squash"
alias gmt="git mergetool"
alias gp="git push --follow-tags"
alias gpa="git push --all --follow-tags"
alias gpt="git push --tags"
alias gr="git reset"
alias grb="git rebase"
alias gri="git rebase --interactive"
alias grp="git reset --patch"
alias gS="git status"
alias gs="git status --short"
alias gSa="git status -uall"
alias gsa="git status -uall --short"
alias gt="git stash"
alias gta="git stash apply"
alias gtl="git stash list"
alias gtp="git stash pop"

# ls
alias l="exa -1"
alias la="exa -la"
alias lat="exa -laT"
alias ll="exa -l"
alias lr="exa -lR"
alias ls="exa"
alias lt="exa -lT"

# terraform
alias tf="terraform"
alias tfa="terraform apply"
alias tfap="terraform apply terraform.tfplan"
alias tfp="terraform plan -out terraform.tfplan"
alias tfw="terraform workspace"
